repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-toml
    - id: check-vcs-permalinks
    - id: check-xml
    - id: check-yaml
    - id: destroyed-symlinks
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        description: "Run 'mypy' for Python type checking"
        language: system
        entry: mypy
        types_or: [python, pyi]
        require_serial: true
      - id: ruff-check
        name: ruff check
        description: "Run 'ruff check' for extremely fast Python linting"
        language: system
        entry: ruff check --force-exclude
        types_or: [python, pyi, jupyter]
        require_serial: true
      - id: ruff-format
        name: ruff format
        description: "Run 'ruff format' for extremely fast Python formatting"
        language: system
        entry: ruff format --force-exclude
        types_or: [python, pyi, jupyter]
        require_serial: true
