#!/bin/bash

# combustion: network prepare
umask 077 # Required for NM config.
mkdir -p /etc/NetworkManager/system-connections/
cat >/etc/NetworkManager/system-connections/eth0.nmconnection <<-EOF

[connection]
id=eth0
type=ethernet
interface-name=eth0

[ipv4]
dns-search=
method=manual
address1=192.168.1.20/24,192.168.1.1
dns=9.9.9.9;149.112.112.112;1.1.1.1

[ipv6]
dns-search=
addr-gen-mode=eui64
method=auto
dns=2620:fe::fe;2620:fe::9
EOF


if [ "${1-}" = "--prepare" ]; then
  # We set disk-encryption-tool-dracut.encryption credential to
  # "force".  This will make disk-encryption-tool-dracut force the
  # encryption, ignoring that Combustion configured the system, and
  # will skip the permission countdown.
  #
  # After the encryption the recovery key is registered in the
  # kernel keyring %user:cryptenroll.
  mkdir -p /run/credstore
  echo "force" > /run/credstore/disk-encryption-tool-dracut.encrypt

  exit 0
fi

# Redirect output to the console.
exec > >(exec tee -a /dev/tty0) 2>&1

# Disk Encryption
#
# Create a valid machine-id, as this will be required to create later
# the host secret.
systemd-machine-id-setup
# We want to persist the host secret key created via systemd-cred
# (/var/lib/systemd/credential.secret).
mount /var
mkdir -p /etc/credstore.encrypted
credential="$(mktemp disk-encryption-tool.XXXXXXXXXX)"
# Enroll extra password.
echo "{{ disk_passwd }}" > "$credential"
systemd-creds encrypt --name=sdbootutil-enroll.pw "$credential" \
               /etc/credstore.encrypted/sdbootutil-enroll.pw
# Enroll TPM2.
echo "1" > "$credential"
systemd-creds encrypt --name=sdbootutil-enroll.tpm2 "$credential" \
             /etc/credstore.encrypted/sdbootutil-enroll.tpm2
shred -u "$credential"
# Unmount /var to not confuse tukit later.
umount /var

# Set keyboard layout.
systemd-firstboot --force --keymap=gb

# Set timezone.
systemd-firstboot --force --timezone=Europe/London

# Install locales.
zypper --non-interactive install glibc-locale

# Leave a marker.
echo "Configured with combustion" > /etc/issue.d/combustion

# Close outputs and wait for tee to finish.
exec 1>&- 2>&-; wait;
